### ISSUE TITLE
ESP32 with vector_datatype 

### ISSUE THREAD

**Issue by MohamedGaberZidan** [RCmags/vector_datatype#1]
Hello,

I'm trying to run IMUfilter library with ESP32, but I got some errors, hope you can help me with that.
Once I include your library and initiate instance it throw an exception and make esp32 keep resseting 

Sorry for your time, I will be very grateful if you can help me. Thanks in advance.

Sincerely,
Zidan

**Comment by RCmags** [comment]
Ok. Can you run this library (vector_datatype) on its own without any errors? Can you compile the examples without issue?

Also, you mention an exception. What is it? Please post the error message.

**Comment by MohamedGaberZidan** [comment]
Hi, 
Thanks for your response, really appreciate it. Yes, I tried to run both examples, there are working good without any issues

**Comment by RCmags** [comment]
Great! Can you please post the serial output for both examples? 

I want to compare it with the expected results to be sure its working well, despite the code compiling.

**Comment by MohamedGaberZidan** [comment]
Sure,
For quaternions example 
01:58:10.878 -> ⸮⸮⸮⸮⸮E⸮1⸮⸮B8f⸮1. Addition: 
01:58:11.014 -> 		(1.00, 1.00, 0.00, 0.00)
01:58:11.049 -> 
01:58:11.049 -> 2. Subtraction: 
01:58:11.083 -> 		(0.00, 1.00, -1.00, 0.00)
01:58:11.117 -> 
01:58:11.117 -> 3. Negation: 
01:58:11.117 -> 		(0.00, -1.00, 1.00, 0.00)
01:58:11.152 -> 
01:58:11.152 -> 4. Increment: 
01:58:11.152 -> 		(0.00, -1.00, 1.00, 1.00)
01:58:11.186 -> 
01:58:11.186 -> 5. Decrement: 
01:58:11.221 -> 		(-1.00, -1.00, 1.00, 1.00)
01:58:11.254 -> 
01:58:11.254 -> 6A. Scalar product: 
01:58:11.254 -> 		(-5.00, -5.00, 5.00, 5.00)
01:58:11.288 -> 
01:58:11.288 -> 6B. Scalar product (reverse order): 
01:58:11.355 -> 		(15.00, 15.00, -15.00, -15.00)
01:58:11.388 -> 
01:58:11.388 -> 7. Scalar divide: 
01:58:11.388 -> 		(1.87, 1.87, -1.87, -1.87)
01:58:11.422 -> 
01:58:11.422 -> 8. Scalar self multiply: 
01:58:11.456 -> 		(18.75, 18.75, -18.75, -18.75)
01:58:11.490 -> 
01:58:11.490 -> 9. Scalar self divide: 
01:58:11.525 -> 		(9.38, 9.38, -9.38, -9.38)
01:58:11.559 -> 
01:58:11.559 -> 10A. Element-wise multiply
01:58:11.593 -> 		(0.00, 0.00, 0.00, -9.38)
01:58:11.593 -> 
01:58:11.593 -> 10B. Self Element-wise multiply
01:58:11.628 -> 		(0.00, 0.00, 0.00, 87.89)
01:58:11.663 -> 
01:58:11.663 -> 11. Quaternion multiply: 
01:58:11.697 -> 		(9.38, 9.38, -9.38, -9.38)
01:58:11.731 -> 
01:58:11.731 -> 12. Quaternion division: 
01:58:11.765 -> 		(9.38, -9.38, 9.38, -9.38)
01:58:11.799 -> 
01:58:11.799 -> 13. Quaternion self multiply: 
01:58:11.833 -> 		(-9.38, 9.38, 9.38, -9.38)
01:58:11.866 -> 
01:58:11.866 -> 14. Quaternion self divide: 
01:58:11.899 -> 		(-9.38, -9.38, 9.38, 9.38)
01:58:11.899 -> 
01:58:11.933 -> 15. Conjugate: 
01:58:11.933 -> 		(-9.38, 9.38, -9.38, -9.38)
01:58:11.967 -> 
01:58:11.967 -> 16. Normalize: 
01:58:12.001 -> 		(-0.50, -0.50, 0.50, 0.50)
01:58:12.001 -> 
01:58:12.001 -> 17. Inner product: 351.56
01:58:12.035 -> 18. Magnitude: 18.75
01:58:12.068 -> 
01:58:12.068 -> 19. Quaternion and array addition: 
01:58:12.102 -> 		(-8.38, -7.37, 12.38, 13.38)
01:58:12.136 -> 
01:58:12.136 -> 20. Quaternion and array subtraction: 
01:58:12.170 -> 		(-10.38, -11.38, 6.37, 5.37)
01:58:12.205 -> 
01:58:12.205 -> 21. Quaternion and array multiply: 
01:58:12.239 -> 		(-56.25, -18.75, 37.50, -75.00)
01:58:12.273 -> 
01:58:12.273 -> 22. Array conversion (multiply): 
01:58:12.341 -> 		(3.00, 6.00, 9.00, 12.00)
01:58:12.341 -> 
01:58:12.341 -> 23. Array conversion (divide): 
01:58:12.375 -> 		(0.10, 0.20, 0.30, 0.40)
01:58:12.409 -> 
01:58:12.409 -> 24. Quaternion and vector addition: 
01:58:12.444 -> 		(-9.38, -8.38, 11.38, 12.38)
01:58:12.479 -> 
01:58:12.479 -> 25. Quaternion and vector subtraction: 
01:58:12.548 -> 		(-9.38, -10.38, 7.37, 6.37)
01:58:12.582 -> 
01:58:12.582 -> 26. Quaternion and vector multiply; 
01:58:12.616 -> 		(-37.50, 0.00, 18.75, -56.25)
01:58:12.650 -> 
01:58:12.650 -> 27. Rotate by axis and angle (Global): 
01:58:12.685 -> 		(0.80, 0.00, -0.49)
01:58:12.719 -> 
01:58:12.719 -> 28. Rotate by axis and angle (local): 
01:58:12.753 -> 		(0.80, 0.00, 0.49)
01:58:12.786 -> 
01:58:12.786 -> 29. Rotate by unit vector: 
01:58:12.786 -> 		(0.00, 0.00, -1.00)
01:58:12.820 -> 
01:58:12.820 -> 30. X-axis vector: 
01:58:12.854 -> 		(0.87, 0.00, -0.50)
01:58:12.854 -> 
01:58:12.888 -> 31. Y-axis vector: 
01:58:12.888 -> 		(0.00, 1.00, 0.00)
01:58:12.922 -> 
01:58:12.922 -> 32. Z-axis vector: 
01:58:12.922 -> 		(0.50, 0.00, 0.87)
01:58:12.956 -> 

##################################################
For vector example

02:00:26.198 -> Hŀ⸮
02:00:26.198 -> ⸮#q⸮$⸮ Gp)⸮1. Addition: 
02:00:26.333 -> 		(1.00, 1.00, 0.00)
02:00:26.366 -> 
02:00:26.366 -> 2. Subtraction: 
02:00:26.366 -> 		(1.00, 1.00, -1.00)
02:00:26.400 -> 
02:00:26.400 -> 3. Negation: 
02:00:26.400 -> 		(-1.00, -1.00, 1.00)
02:00:26.433 -> 
02:00:26.433 -> 4. Increment: 
02:00:26.468 -> 		(-1.00, 0.00, 1.00)
02:00:26.468 -> 
02:00:26.468 -> 5. Decrement: 
02:00:26.501 -> 		(-2.00, 0.00, 1.00)
02:00:26.501 -> 
02:00:26.501 -> 6A. Scalar product: 
02:00:26.536 -> 		(-10.00, 0.00, 5.00)
02:00:26.569 -> 
02:00:26.569 -> 6B. Scalar product (reverse order): 
02:00:26.603 -> 		(30.00, 0.00, -15.00)
02:00:26.636 -> 
02:00:26.636 -> 7. Scalar divide: 
02:00:26.636 -> 		(3.75, 0.00, -1.87)
02:00:26.670 -> 
02:00:26.670 -> 8. Self multiply: 
02:00:26.704 -> 		(37.50, 0.00, -18.75)
02:00:26.704 -> 
02:00:26.704 -> 9. Self divide: 
02:00:26.737 -> 		(1.87, 0.00, -0.94)
02:00:26.770 -> 
02:00:26.770 -> 10A. Element-wise multiply
02:00:26.804 -> 		(0.00, 0.00, -0.94)
02:00:26.804 -> 
02:00:26.804 -> 10B. Self Element-wise multiply
02:00:26.839 -> 		(0.00, 0.00, 0.88)
02:00:26.874 -> 
02:00:26.874 -> 11. Normalize vector: 
02:00:26.908 -> 		(0.89, 0.00, -0.45)
02:00:26.908 -> 
02:00:26.908 -> 12. Cross product: 
02:00:26.942 -> 		(0.00, -0.94, 0.00)
02:00:26.975 -> 
02:00:26.975 -> 13. Dot product: -0.94
02:00:27.008 -> 14. Magnitude: 0.94
02:00:27.008 -> 
02:00:27.008 -> 15. Vector and array addition: 
02:00:27.043 -> 		(1.00, 1.06, 3.00)
02:00:27.077 -> 
02:00:27.077 -> 16. Vector and array subtraction: 
02:00:27.111 -> 		(-1.00, -2.94, -3.00)
02:00:27.144 -> 
02:00:27.144 -> 17. Vector and array cross product: 
02:00:27.177 -> 		(-2.81, 0.00, 0.94)
02:00:27.211 -> 
02:00:27.211 -> 18. Dot product (array): -1.87
02:00:27.244 -> 
02:00:27.244 -> 19. Array conversion (multiply): 
02:00:27.278 -> 		(3.00, 6.00, 9.00)
02:00:27.278 -> 
02:00:27.278 -> 20. Array conversion (divide): 
02:00:27.345 -> 		(0.10, 0.20, 0.30)
02:00:27.345 ->

**Comment by RCmags** [comment]
Thanks. I've checked the output with my own and it matches. 
Well, it seems this library is working. Let's move onto to next one.

**Comment by MohamedGaberZidan** [comment]
I think it works well

02:26:44.219 -> =======================================================
02:26:44.253 -> temp : 30.67
02:26:44.287 -> accX : 1.01	accY : 0.01	accZ : 0.07
02:26:44.321 -> gyroX : -0.07	gyroY : 0.10	gyroZ : 0.12
02:26:44.355 -> accAngleX : 0.80	accAngleY : -85.91
02:26:44.388 -> gyroAngleX : 14.16	gyroAngleY : -0.20	gyroAngleZ : -0.39
02:26:44.456 -> angleX : 0.32	angleY : -85.89	angleZ : -0.39
02:26:44.524 -> =======================================================
02:26:44.558 -> 
02:26:45.439 -> =======================================================
02:26:45.507 -> temp : 30.76
02:26:45.507 -> accX : 1.01	accY : 0.01	accZ : 0.07
02:26:45.540 -> gyroX : -0.13	gyroY : 0.08	gyroZ : 0.07
02:26:45.608 -> accAngleX : 0.66	accAngleY : -85.79
02:26:45.643 -> gyroAngleX : 14.00	gyroAngleY : -0.10	gyroAngleZ : -0.40
02:26:45.711 -> angleX : 0.35	angleY : -85.94	angleZ : -0.40
02:26:45.745 -> =======================================================
02:26:45.813 -> 
02:26:46.659 -> =======================================================
02:26:46.727 -> temp : 30.81
02:26:46.727 -> accX : 1.02	accY : 0.01	accZ : 0.07
02:26:46.795 -> gyroX : 0.02	gyroY : 0.08	gyroZ : -0.05
02:26:46.828 -> accAngleX : 0.48	accAngleY : -86.05
02:26:46.862 -> gyroAngleX : 13.95	gyroAngleY : -0.04	gyroAngleZ : -0.35
02:26:46.930 -> angleX : 0.27	angleY : -85.98	angleZ : -0.35
